# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='url',
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
