# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0002_auto_20190620_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='name',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='content',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='last_edited',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
    ]
